### PR TITLE
Remove custom environment

### PR DESCRIPTION
**Pull request by niceking**
## 💬 Summary of Changes

We've decided to introduce stricter validation of run environment variables client side on Buildkite, so this PR is to remove the `custom_environment` variable from this test collector. 

AFAIK this feature isn't being used for anything atm? It looks like it was possibly used to set `tags` in the past? But `tags` is allowed as a top level environment variable and so can just be sent as part of the run environment, and not embedded as part of the `custom_environment`. Let me know if I am mistaken and you want to keep this `custom_environment` for any reason!

## 🧾 Checklist

- [X] 🧐 Performed a self-review of the changes
- [X] ✅ Added tests to cover changes
- [X] 🏎 Ran Unit Tests and they all passed
- [X] 🏷 Labeled this PR appropriately

### CODE REVIEW

**Comment by iampatbrown** [comment]
Hey @niceking :)

> AFAIK this feature isn't being used for anything atm? It looks like it was possibly used to set tags in the past?

That sounds about right to me. From memory it was only introduced to support tags and experimental features. Removing custom environment support also means it's possible to remove some of what was introduced to support it. For example, [AnyCodable](https://github.com/buildkite/test-collector-swift/pull/54/files#diff-b1438c671d8c6d95063671d6a72a7b09b6c0e30787fc9c26daacb309c8730e18R4) is no longer needed and the coding keys for [RunEnvironment](https://github.com/buildkite/test-collector-swift/pull/54/files#diff-c16e84916400a9c1d7f52e60abdf2e747eae165959d615a4626b65c0d194a0baL45-R100) can be defined using an enum again.

A lot of what was added in #54 can be removed :)

**Comment by niceking** [comment]
Thanks @iampatbrown! I've added two commits, do they look about right? I have never actually written any Swift before 😂 

I also had a read through #54 for anything else that should potentially also be removed? Nothing stood out to me, except maybe this entire [dictionary function](https://github.com/buildkite/test-collector-swift/pull/54/files#diff-452ee96e192c721936d7dcb13cf70ced3ea3b2df7d71e751a6fe464f5da36d7dR27) could be removed? I wasn't too sure what this was doing but perhaps nothing used it other than the customEnvironment? I did edit this method signature as part of the AnyCodable removal but maybe the whole method could be removed?

**Comment by iampatbrown** [comment]
> Nothing stood out to me, except maybe this entire [dictionary function](https://github.com/buildkite/test-collector-swift/pull/54/files#diff-452ee96e192c721936d7dcb13cf70ced3ea3b2df7d71e751a6fe464f5da36d7dR27) could be removed?

Yeah, that looks fine to remove as well :)

I've just removed it for you so I can approve now. The rest looks good. 

> I have never actually written any Swift before 😂

It looks like you're getting the hang of it pretty quickly :) well done!

**Review by iampatbrown — APPROVED** [review]

**Comment by niceking** [comment]
Hey @iampatbrown! I thought it would be a good idea to put support for `tags` as a env var back in (as it was taken out of custom env) as we do accept this env var...but I don't really understand Swift 😅 I've given it a go in my previous commit, but help?

**Comment by niceking** [comment]
@iampatbrown okay I had maybe an epiphany in the shower about this bit of code 😅 

Was the `custom_environment` a way for a user to put in arbitrary extra env variables? So it was the contents inside `custom_environment` that were merged with the env and sent, and NOT the `custom_environment` as a key? 

i.e. if my `custom_environment` was 
```
[
  "greeting": "hi"
]
```

then the env becomes:
```
 [
        "CI": "ci",
        "key": "key",
        ...
        "greeting": "hi"
  ]
```

NOT: 

```
 [
        "CI": "ci",
        "key": "key",
        ...
        "custom_environment": [
            "greeting": "hi"
         ]
  ]
```

If so, I think maybe this whole PR can be closed? The context is I am doing a piece of work that enforced a whitelist of allowed env vars on Buildkite's end, and I thought that "custom_environment" was a random env var that the Swift collector was sending through. But actually I think its just a way of appending / overwriting defaults in the Swift env? 

I think this can just continue behaving as is, as we'll filter out what we don't want server side, and it would be annoying to have to update the Swift client every time we introduce a new env var a user could potentially want to set

**Comment by iampatbrown** [comment]
> okay I had maybe an epiphany in the shower about this bit of code 😅
> Was the custom_environment a way for a user to put in arbitrary extra env variables?

@niceking 😅 your epiphany was correct!

[RunEnvironmentTests.swift](https://github.com/buildkite/test-collector-swift/blob/main/Tests/CoreTests/RunEnvironmentTests.swift) has a test demonstrating the behaviour:

https://github.com/buildkite/test-collector-swift/blob/73c3228c75925b560b7605bb84ac95e4f9c31bfb/Tests/CoreTests/RunEnvironmentTests.swift#L124-L169


> I think this can just continue behaving as is, as we'll filter out what we don't want server side, as it would be annoying to have to update the Swift client every time we introduce a new env var a user could potentially want to set.

`custom_environment` was added for this reason. It meant new environment variables could be tested before being added to the public api. In particular, the tags feature. 

> I thought it would be a good idea to put support for tags as a top level env var back in

If the tags feature is now public, it might be worth adding it anyway. It would depend on how the other collectors are handling it.

**Comment by niceking** [comment]
Ha ok thanks for confirming @iampatbrown! Well at least I feel like I learned a little bit of Swift along the way!

I don't think the tags feature is public yet, so I think that the best thing would be to just close this PR, and leave everything as is. Can always add tags to the main env var config later when it does become public :)

**Pull request closed without merging**
