### PR TITLE
Fix a typo in an environment var name "ANA**N**LYTICS"

### PR DESCRIPTION
**Pull request by mokagio**
## 💬 Summary of Changes

I noticed this minor typo when looking at the source code. At least, I am 99.9% sure it's a typo 😅 

## 🧾 Checklist

- [x] 🧐 Performed a self-review of the changes
- [x] ✅ Added tests to cover changes – N.A.
- [x] 🏎 Ran Unit Tests and they all passed – Yes, with `swift test`
- [x] 🏷 Labeled this PR appropriately – I don't have access rights to add labels to issues or PRs in this repo

## 📝 Items of Note

N.A.

### CODE REVIEW

**Comment by mokagio** [comment]
@iampatbrown I can't add you as a reviewer via the GitHub UI, so here's a direct ping. Thanks 🙇‍♂️

**Comment by iampatbrown** [comment]
Thanks @mokagio. Good catch :) I had this fixed on the next update as well :P Just finalising some testing around the environment variables. 

Also, I mentioned you to the Buildkite team yesterday. I hope that's okay. I said you might be able to provide some feedback regarding the Swift collector as well as test analytics in general. Possibly help prioritise features that will benefit you and your team the most.

**Comment by iampatbrown** [comment]
> At least, I am 99.9% sure it's a typo
Yes 100% a typo :)

**Comment by mokagio** [comment]
> Also, I mentioned you to the Buildkite team yesterday. I hope that's okay. 

It is. We had an intro call with Keith and someone else (someone from sales or dev relationship) back when Automattic setup a trial for Buildkite and we did express interest in Test Analytics.

> I said you might be able to provide some feedback regarding the Swift collector as well as test analytics in general. Possibly help prioritise features that will benefit you and your team the most.

Sure thing! I have some thoughts already, just lack the time to take a step back and write them properly.

**Comment by iampatbrown** [comment]
> We had an intro call with Keith
Awesome.
> I have some thoughts already, just lack the time to take a step back and write them properly.
No worries. Likewise! :) if anything urgent pops up, let me know. 
Also, thanks again for the PR!

**Pull request merged**
